"use client";
import { useEffect, useRef } from "react";
import { mountGame } from "../lib/game";
export default function SiegeGame() {
    const root = useRef<HTMLDivElement>(null);
    useEffect(() => { if (!root.current)
        return; return mountGame(root.current); }, []);
    return <div ref={root}><header><a className="brand" href="./">ᠮ <span>SUBUTAI<span className="small">СҮБЭЭДЭЙН БҮСЛЭЛТ</span></span></a><div className="chapter">THE LAST GATE <span>•</span> 01</div><button id="sound" aria-label="Дуу асаах">ДУУ: OFF</button></header><main><div className="topline"><span>МӨНХ ТЭНГЭРИЙН ДОР</span><span id="status">ТУЛААНД БЭЛЭН</span></div><section className="arena"><canvas id="game" aria-label="Сүбээдэйн бүслэлт тоглоом"></canvas><div className="hud"><div><label>АМИН ХҮЧ</label><div className="health"><i id="hp"></i></div></div><div className="score"><label>ОНОО</label><strong id="score">0000</strong></div><div className="wave"><label>ДАВАЛГАА</label><strong id="wave">01 / 03</strong></div></div><div className="gatehud"><label>ЦАЙЗЫН ХААЛГА</label><div><i id="gate"></i></div></div><div id="overlay"><div className="eyebrow">THE STEPPE REMEMBERS</div><h1>СҮБЭЭДЭЙН<br /><em>БҮСЛЭЛТ</em></h1><p id="message">Гурван давалгааг дав. Хаалгыг нураа.<br />Тал нутгийн домгийг үргэлжлүүл.</p><button id="start">ТУЛААНД ОРОХ <span>↗</span></button><div className="hint">WASD хөдөлгөөн · Хулганаар онил · Дарж харва</div></div><div id="toast"></div><div className="mobile"><div className="dpad"><button data-key="w">▲</button><button data-key="a">◀</button><button data-key="s">▼</button><button data-key="d">▶</button></div><button id="mobileFire">ХАРВА</button></div></section><footer><div><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd><span>Хөдөлгөөн</span></div><div><kbd>CLICK</kbd><span>Сум харвах</span></div><div><kbd>SPACE</kbd><span>Огцом бултах</span></div><div><kbd>P</kbd><span>Түр зогсоох</span></div><span className="footnote">НЭГ БААТАР. НЭГ ЦАЙЗ.</span></footer></main></div>;
}
